###############################################################################
#
#   Software to be installed in the environment
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: maciej.bak@unibas.ch
#   CREATED: 04-07-2020
#   LICENSE: Apache_2.0
#
###############################################################################
---

  name: bindz-dev
      
  channels:
    - bioconda
    - conda-forge
      
  dependencies:
    - bash=4.4.18
    - beautysh=6.0.1
    - coverage=5.1
    - curl=7.68.0
    - flake8=3.8.3
    - graphviz=2.38.0
    - jinja2=2.10
    - pandas=1.0.1
    - pulp=1.6.8
    - pytest=5.4.3
    - python=3.7.4
    - pyyaml=3.12
    - shellcheck=0.7.0
    - snakemake=5.24.2
    - unzip=6.0
  
...
