###############################################################################
#
#   Config options for the snakemake pipeline
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: maciej.bak@unibas.ch
#   CREATED: 09-04-2020
#   LICENSE: Apache_2.0
#
###############################################################################
---

# absolute path to the pipeline root directory
pipeline_path:

# input sequence from the user
sequence:

# absolute paths to the directory with TRANSFAC-formatted PWM files
# and corresponding sequence logos directory
pwm_directory:
seqlogos_directory:

# absolute path for the output directory
outdir:

# MotEvo parameter: prior probability for the background binding
MotEvo_bg_binding_prior: 0.99

# MotEvo parameter: prior minimum binding posterior probability
MotEvo_min_binding_posterior: 0.01

# MotEvo parameter: order of the Markov chain
MotEvo_Markov_chain_order: 1

...
