###############################################################################
#
#   Config options for the snakemake pipeline
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: maciej.bak@unibas.ch
#   CREATED: 09-04-2020
#   LICENSE: Apache_2.0
#
###############################################################################
---

# absolute path to the pipeline root directory
pipeline_path:

# name of the user's sequence
# Please do not use spaces
seq_name:
# input sequence from the user
sequence:

# path to the directory with TRANSFAC-formatted PWM files
#
# Please use an absolute path or a path relative to the
# pipeline root directory
pwm_directory:

# path for the output directory
#
# Please use an absolute path or a path relative to the
# pipeline root directory
outdir:

# MotEvo parameter: prior probability for the background binding
MotEvo_bg_binding_prior:

# MotEvo parameter: prior minimum binding posterior probability
MotEvo_min_binding_posterior:

# MotEvo parameter: order of the Markov chain
MotEvo_Markov_chain_order:

...
