name: ci

on: push

jobs:

  setup-env:
    runs-on: [ubuntu-20.04, macOS-10.15]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup miniconda & bindz root env
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7.4
          miniconda-version: 4.7.12
          auto-update-conda: false
          environment-file: envs/main.yml
          activate-environment: bindz
          auto-activate-base: false

      - name: Display all miniconda & env info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list


