name: install

on: push

jobs:

  install-script:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 4.7.12
          auto-update-conda: false

      - name: Display all miniconda & env info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: Execute install script
        shell: bash -l {0}
        run: bash install.sh

      - name: Test bindz command
        shell: bash -l {0}
        run: |
          source $HOME/.bashrc
          bindz
